# Default Log Format (.txt, .log, etc,)
# If you dont know what to do, then Dont change anything
logformat: txt
# Default User Phone Number:
# Please use the -, because Spaces might corrupt the config.
phonenum: 55-555-555-5555 
# Use phone Number:
usphonenum: true
# Use email (for Paypal and like accounts):
usemail: false
# Paypal (or related) email account:
emailacc: myemail@acooldoma.in
# Unique Code character limit, Do not use more than 50, or it will be bad!:
# Limits the UC Character limit for e.g: 123456 to 1234 (Randomly Generated)
ucchlmt: 6
# Write the email for Donations Email
emailuc: myemail@acooldoma.in
# For more info go to the wiki at:
# http://github.com/TheKillerTacos/DonateRank/
